# Configuration
substitutions:
  # Dashes are not supported in devicename
  name: "camprivacyshield01"
  friendly_name: "Cam Privacy Shield 01 - Hallway"
  device_description: 'Camera Privacy Shield'
  project_version: '1.0'
  loglevel: VERBOSE
  update_interval: 1min

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  comment: '${device_description}'
  name_add_mac_suffix: false

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.project-template
    version: '${project_version}'

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Fw2Ql2lsZK9fEO2nvJ8e4tRfROonWlUxD63ShxueRfM="

ota:
  password: "fbf0d033b54f5a7158d663ec8f378e25"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

dashboard_import:
  package_import_url: github://balzreber/esphome_configs/camPrivacyShield.yaml@main
  import_full_config: true

time:
  - platform: homeassistant

switch:
  - platform: template
    name: "Close"
    id: move_switch
    icon: 'mdi:security'
    optimistic: true
    turn_on_action:
      - stepper.set_target:
          id: doorstepper
          target: -5100
    turn_off_action:
      - stepper.set_target:
          id: doorstepper
          target: 0

stepper:
  - platform: uln2003
    id: doorstepper
    pin_a: GPIO12
    pin_b: GPIO14
    pin_c: GPIO27
    pin_d: GPIO26
    max_speed: 200 steps/s
    sleep_when_done: true

# binary_sensor:
#   - platform: gpio
#     pin: GPIO32
#     name: "endswitch_r"
#     id: endswitch_r
#     filters:
#       - delayed_on: 100ms
#     on_click:
#       min_length: 10ms
#       then:
#         - stepper.report_position:
#             id: doorstepper
#             position: 0
#         - stepper.set_target:
#             id: doorstepper
#             target: 0
#   - platform: gpio
#     pin: GPIO33
#     name: "endswitch_l"
#     id: endswitch_l
#     filters:
#       - delayed_on: 100ms
#     on_click:
#       min_length: 10ms
#       then:
#         - stepper.report_position:
#             id: doorstepper
#             position: 0
#         - stepper.set_target:
#             id: doorstepper
#             target: 0

button:
  - platform: restart
    name: 'Restart'
    icon: 'mdi:restart'
  - platform: template
    name: "Move Open"
    id: moveplus_btn
    icon: 'mdi:plus-circle-outline'
    entity_category: config
    on_press:
      - stepper.report_position:
            id: doorstepper
            position: 0
      - stepper.set_target:
          id: doorstepper
          target: 200
  - platform: template
    name: "Move Close"
    id: moveminus_btn
    icon: 'mdi:minus-circle-outline'
    entity_category: config
    on_press:
      - stepper.report_position:
            id: doorstepper
            position: 0
      - stepper.set_target:
          id: doorstepper
          target: -200
  - platform: template
    name: "Reset Home Position"
    id: resethome_btn
    icon: 'mdi:null'
    entity_category: config
    on_press:
      - stepper.report_position:
            id: doorstepper
            position: 0
      - stepper.set_target:
            id: doorstepper
            target: 0

text_sensor:
  - platform: template
    name: 'Version'
    icon: 'mdi:application-brackets-outline'
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};
    update_interval: 6h
  - platform: version
    name: 'ESPHome Version'
    icon: 'mdi:raspberry-pi'
    entity_category: diagnostic
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: 'IP'
      icon: 'mdi:ip-outline'
    ssid:
      name: 'Connected WiFi'
      icon: 'mdi:wifi'

sensor:
  - platform: wifi_signal
    name: 'WiFi Signal'
    update_interval: $update_interval
    icon: mdi:wifi-strength-1