# Configuration
substitutions:
  # Dashes are not supported in devicename
  name: "ledstripdevelopment01"
  friendly_name: "LED Strip Development 01"
  device_description: 'bHive LED Strip Controller'
  project_version: '0.1'
  loglevel: DEBUG
  update_interval: 1min

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  comment: '${device_description}'
  name_add_mac_suffix: false

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.project-template
    version: '${project_version}'

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Fw2Ql2lsZK9fEO2nvJ8e4tRfROonWlUxD63ShxueRfM="

ota:
  password: "fbf0d033b54f5a7158d663ec8f378e25"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

dashboard_import:
  package_import_url: github://balzreber/esphome_configs/ledController.yaml@main
  import_full_config: false

time:
  - platform: homeassistant

text_sensor:
  - platform: template
    name: 'Version'
    icon: 'mdi:application-brackets-outline'
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};
    update_interval: 6h
  - platform: version
    name: 'ESPHome Version'
    icon: 'mdi:raspberry-pi'
    entity_category: diagnostic
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: 'IP'
      icon: 'mdi:ip-outline'
    ssid:
      name: 'Connected WiFi'
      icon: 'mdi:wifi'

sensor:
  - platform: wifi_signal
    name: 'WiFi Signal'
    update_interval: $update_interval
    icon: mdi:wifi-strength-1